version: '3'

services:
  mariadb:
    image: mariadb:11.0.1-rc
    container_name: mariadb-db
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-toor}
      MYSQL_DATABASE: ${DB_NAME:-mariadb}
    ports:
      - ${DB_PORT:-3306}:3306