version: '3.9'

services:
  backend:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mariadb:11.0.1-rc
    restart: always
    environment:
      MARIADB_DATABASE: mariadb
      MARIADB_ROOT_PASSWORD: toor
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 3306:3306
