name: Deployment
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v3
            - name: Cache dependencies
              uses: actions/cache@v3
              with:
                  path: ~/.npm
                  key: deps-node-module-${{hashFiles('**/package-lock.json')}}
            - name: Install dependencies
              run: npm ci
            - name: Build Proyects
              run: npm run build
            - name: Publish JS filename
              id: publish
              run: find dist/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'
            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: dist-files
                  path: dist
    deploy:
        needs: build
        uses: ./.github/workflows/08-reusable.yml
        with:
            artifact-name: dist-files
